console.log("\ntask2:");
let fruit="apple,orange,banana";
console.log(fruit);
let num=123;
console.log(num);
let judge=true;
let judge2=2<1;
console.log(judge);
console.log(judge2);
console.log("\n数据类型：");
console.log(typeof fruit);
console.log(typeof num);
console.log(typeof judge);
console.log(typeof judge2);
console.log("\n运算：");
console.log(num+2233);
console.log(num-23);
console.log(num*3);
console.log(num/3);
console.log(num%4);